# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\PlotWindow_TR.ui'
#
# Created: Thu Nov 12 11:40:22 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(832, 724)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("DESIGN_Resource/plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_TR_Plot = QtGui.QGridLayout()
        self.gridLayout_TR_Plot.setObjectName(_fromUtf8("gridLayout_TR_Plot"))
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_TR_Plot.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_TR_Plot, 0, 0, 1, 1)
        self.gridLayoutControl_OSA = QtGui.QGridLayout()
        self.gridLayoutControl_OSA.setObjectName(_fromUtf8("gridLayoutControl_OSA"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.doubleSpinBox_MaxIncrement = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_MaxIncrement.setFont(font)
        self.doubleSpinBox_MaxIncrement.setDecimals(0)
        self.doubleSpinBox_MaxIncrement.setMinimum(0.0)
        self.doubleSpinBox_MaxIncrement.setMaximum(100000.0)
        self.doubleSpinBox_MaxIncrement.setSingleStep(1.0)
        self.doubleSpinBox_MaxIncrement.setProperty("value", 1.0)
        self.doubleSpinBox_MaxIncrement.setObjectName(_fromUtf8("doubleSpinBox_MaxIncrement"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_MaxIncrement, 1, 2, 1, 1)
        self.spinBox_MinIncrement = QtGui.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_MinIncrement.setFont(font)
        self.spinBox_MinIncrement.setMinimum(0)
        self.spinBox_MinIncrement.setMaximum(10000)
        self.spinBox_MinIncrement.setSingleStep(1)
        self.spinBox_MinIncrement.setProperty("value", 0)
        self.spinBox_MinIncrement.setObjectName(_fromUtf8("spinBox_MinIncrement"))
        self.gridLayout_3.addWidget(self.spinBox_MinIncrement, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 5, 1, 1, 1)
        self.spinBox_WSMin = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_WSMin.setFont(font)
        self.spinBox_WSMin.setDecimals(3)
        self.spinBox_WSMin.setMinimum(-99.0)
        self.spinBox_WSMin.setSingleStep(0.1)
        self.spinBox_WSMin.setObjectName(_fromUtf8("spinBox_WSMin"))
        self.gridLayout_3.addWidget(self.spinBox_WSMin, 3, 0, 1, 1)
        self.spinBox_WSMax = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_WSMax.setFont(font)
        self.spinBox_WSMax.setDecimals(3)
        self.spinBox_WSMax.setMinimum(-99.0)
        self.spinBox_WSMax.setSingleStep(0.1)
        self.spinBox_WSMax.setObjectName(_fromUtf8("spinBox_WSMax"))
        self.gridLayout_3.addWidget(self.spinBox_WSMax, 3, 2, 1, 1)
        self.spinBox_WDMin = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_WDMin.setFont(font)
        self.spinBox_WDMin.setDecimals(3)
        self.spinBox_WDMin.setMinimum(-99.0)
        self.spinBox_WDMin.setSingleStep(0.1)
        self.spinBox_WDMin.setObjectName(_fromUtf8("spinBox_WDMin"))
        self.gridLayout_3.addWidget(self.spinBox_WDMin, 5, 0, 1, 1)
        self.spinBox_WDMax = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_WDMax.setFont(font)
        self.spinBox_WDMax.setDecimals(3)
        self.spinBox_WDMax.setMinimum(-99.0)
        self.spinBox_WDMax.setSingleStep(0.1)
        self.spinBox_WDMax.setObjectName(_fromUtf8("spinBox_WDMax"))
        self.gridLayout_3.addWidget(self.spinBox_WDMax, 5, 2, 1, 1)
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.doubleSpinBox_LineWidth = QtGui.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_LineWidth.setFont(font)
        self.doubleSpinBox_LineWidth.setDecimals(2)
        self.doubleSpinBox_LineWidth.setMinimum(0.1)
        self.doubleSpinBox_LineWidth.setMaximum(10.0)
        self.doubleSpinBox_LineWidth.setSingleStep(0.1)
        self.doubleSpinBox_LineWidth.setProperty("value", 0.5)
        self.doubleSpinBox_LineWidth.setObjectName(_fromUtf8("doubleSpinBox_LineWidth"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_LineWidth, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.groupBox_2)
        self.checkBox_legend = QtGui.QCheckBox(Form)
        self.checkBox_legend.setChecked(False)
        self.checkBox_legend.setObjectName(_fromUtf8("checkBox_legend"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.checkBox_legend)
        spacerItem1 = QtGui.QSpacerItem(20, 350, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.pushButton_SavePicture = QtGui.QPushButton(Form)
        self.pushButton_SavePicture.setObjectName(_fromUtf8("pushButton_SavePicture"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.pushButton_SavePicture)
        self.checkBox_Grid = QtGui.QCheckBox(Form)
        self.checkBox_Grid.setObjectName(_fromUtf8("checkBox_Grid"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.checkBox_Grid)
        self.gridLayoutControl_OSA.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayoutControl_OSA, 0, 1, 1, 1)
        self.actionSavePicture = QtGui.QAction(Form)
        self.actionSavePicture.setObjectName(_fromUtf8("actionSavePicture"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton_SavePicture, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSavePicture.trigger)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Plot FBG Spectrum", None))
        self.groupBox.setTitle(_translate("Form", "Axis Control", None))
        self.label_2.setText(_translate("Form", "Increments", None))
        self.label.setText(_translate("Form", "to", None))
        self.label_4.setText(_translate("Form", "Wavelength Shift (nm)", None))
        self.label_3.setText(_translate("Form", "to", None))
        self.label_6.setText(_translate("Form", "Peak width variation (nm)", None))
        self.label_7.setText(_translate("Form", "to", None))
        self.groupBox_2.setTitle(_translate("Form", "Line Properties", None))
        self.label_5.setText(_translate("Form", "Line Width:", None))
        self.checkBox_legend.setText(_translate("Form", "Legend", None))
        self.pushButton_SavePicture.setText(_translate("Form", "Save Picture", None))
        self.checkBox_Grid.setText(_translate("Form", "Grid", None))
        self.actionSavePicture.setText(_translate("Form", "SavePicture", None))

