# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\PlotWindow_OSA.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(682, 724)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("DESIGN_Resource/plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_OSA_Plot = QtGui.QGridLayout()
        self.gridLayout_OSA_Plot.setObjectName(_fromUtf8("gridLayout_OSA_Plot"))
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_OSA_Plot.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_OSA_Plot, 0, 0, 1, 1)
        self.gridLayoutControl_OSA = QtGui.QGridLayout()
        self.gridLayoutControl_OSA.setObjectName(_fromUtf8("gridLayoutControl_OSA"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.spinBox_XlimMin = QtGui.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_XlimMin.setFont(font)
        self.spinBox_XlimMin.setMinimum(0)
        self.spinBox_XlimMin.setMaximum(5000)
        self.spinBox_XlimMin.setSingleStep(10)
        self.spinBox_XlimMin.setProperty("value", 1500)
        self.spinBox_XlimMin.setObjectName(_fromUtf8("spinBox_XlimMin"))
        self.gridLayout_3.addWidget(self.spinBox_XlimMin, 1, 0, 1, 1)
        self.doubleSpinBox_XlimMax = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_XlimMax.setFont(font)
        self.doubleSpinBox_XlimMax.setDecimals(0)
        self.doubleSpinBox_XlimMax.setMinimum(0.0)
        self.doubleSpinBox_XlimMax.setMaximum(5000.0)
        self.doubleSpinBox_XlimMax.setSingleStep(10.0)
        self.doubleSpinBox_XlimMax.setProperty("value", 1600.0)
        self.doubleSpinBox_XlimMax.setObjectName(_fromUtf8("doubleSpinBox_XlimMax"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_XlimMax, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 3, 1, 1, 1)
        self.doubleSpinBox_YlimMax = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_YlimMax.setFont(font)
        self.doubleSpinBox_YlimMax.setDecimals(2)
        self.doubleSpinBox_YlimMax.setMinimum(0.0)
        self.doubleSpinBox_YlimMax.setMaximum(2.0)
        self.doubleSpinBox_YlimMax.setSingleStep(0.1)
        self.doubleSpinBox_YlimMax.setProperty("value", 1.0)
        self.doubleSpinBox_YlimMax.setObjectName(_fromUtf8("doubleSpinBox_YlimMax"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_YlimMax, 3, 2, 1, 1)
        self.spinBox_YlimMin = QtGui.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_YlimMin.setFont(font)
        self.spinBox_YlimMin.setMinimum(0)
        self.spinBox_YlimMin.setMaximum(2)
        self.spinBox_YlimMin.setSingleStep(1)
        self.spinBox_YlimMin.setProperty("value", 0)
        self.spinBox_YlimMin.setObjectName(_fromUtf8("spinBox_YlimMin"))
        self.gridLayout_3.addWidget(self.spinBox_YlimMin, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 2, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 2)
        self.comboBox_LineColorUndeformed = QtGui.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_LineColorUndeformed.setFont(font)
        self.comboBox_LineColorUndeformed.setObjectName(_fromUtf8("comboBox_LineColorUndeformed"))
        self.comboBox_LineColorUndeformed.addItem(_fromUtf8(""))
        self.comboBox_LineColorUndeformed.addItem(_fromUtf8(""))
        self.comboBox_LineColorUndeformed.addItem(_fromUtf8(""))
        self.comboBox_LineColorUndeformed.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_LineColorUndeformed, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.comboBox_LineColorSimulated = QtGui.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_LineColorSimulated.setFont(font)
        self.comboBox_LineColorSimulated.setObjectName(_fromUtf8("comboBox_LineColorSimulated"))
        self.comboBox_LineColorSimulated.addItem(_fromUtf8(""))
        self.comboBox_LineColorSimulated.addItem(_fromUtf8(""))
        self.comboBox_LineColorSimulated.addItem(_fromUtf8(""))
        self.comboBox_LineColorSimulated.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_LineColorSimulated, 3, 1, 2, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBox_LineWidth = QtGui.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_LineWidth.setFont(font)
        self.doubleSpinBox_LineWidth.setDecimals(2)
        self.doubleSpinBox_LineWidth.setMinimum(0.1)
        self.doubleSpinBox_LineWidth.setMaximum(10.0)
        self.doubleSpinBox_LineWidth.setSingleStep(0.1)
        self.doubleSpinBox_LineWidth.setProperty("value", 0.5)
        self.doubleSpinBox_LineWidth.setObjectName(_fromUtf8("doubleSpinBox_LineWidth"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_LineWidth, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.groupBox_2)
        self.checkBox_legend = QtGui.QCheckBox(Form)
        self.checkBox_legend.setChecked(False)
        self.checkBox_legend.setObjectName(_fromUtf8("checkBox_legend"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.checkBox_legend)
        spacerItem1 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout.setItem(8, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.pushButton_SavePicture = QtGui.QPushButton(Form)
        self.pushButton_SavePicture.setObjectName(_fromUtf8("pushButton_SavePicture"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.pushButton_SavePicture)
        self.checkBox_Grid = QtGui.QCheckBox(Form)
        self.checkBox_Grid.setObjectName(_fromUtf8("checkBox_Grid"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.checkBox_Grid)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.textEdit_FBGoutput = QtGui.QTextEdit(self.groupBox_3)
        self.textEdit_FBGoutput.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_FBGoutput.setFont(font)
        self.textEdit_FBGoutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_FBGoutput.setObjectName(_fromUtf8("textEdit_FBGoutput"))
        self.gridLayout_6.addWidget(self.textEdit_FBGoutput, 0, 0, 1, 1)
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.groupBox_3)
        self.gridLayoutControl_OSA.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayoutControl_OSA, 0, 1, 1, 1)
        self.actionSavePicture = QtGui.QAction(Form)
        self.actionSavePicture.setObjectName(_fromUtf8("actionSavePicture"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton_SavePicture, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSavePicture.trigger)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Plot FBG Spectrum", None))
        self.groupBox.setTitle(_translate("Form", "Axis Control", None))
        self.label_3.setText(_translate("Form", "to", None))
        self.label.setText(_translate("Form", "to", None))
        self.label_4.setText(_translate("Form", "Reflectivity (R)", None))
        self.label_2.setText(_translate("Form", "Wavelength (nm)", None))
        self.groupBox_2.setTitle(_translate("Form", "Line Properties", None))
        self.label_8.setText(_translate("Form", "Simulated Spectrum", None))
        self.label_6.setText(_translate("Form", "Line Color:", None))
        self.comboBox_LineColorUndeformed.setItemText(0, _translate("Form", "grey", None))
        self.comboBox_LineColorUndeformed.setItemText(1, _translate("Form", "blue", None))
        self.comboBox_LineColorUndeformed.setItemText(2, _translate("Form", "red", None))
        self.comboBox_LineColorUndeformed.setItemText(3, _translate("Form", "black", None))
        self.label_7.setText(_translate("Form", "Undeformed Spectrum ", None))
        self.comboBox_LineColorSimulated.setItemText(0, _translate("Form", "blue", None))
        self.comboBox_LineColorSimulated.setItemText(1, _translate("Form", "red", None))
        self.comboBox_LineColorSimulated.setItemText(2, _translate("Form", "black", None))
        self.comboBox_LineColorSimulated.setItemText(3, _translate("Form", "grey", None))
        self.label_5.setText(_translate("Form", "Line Width:", None))
        self.checkBox_legend.setText(_translate("Form", "Legend", None))
        self.pushButton_SavePicture.setText(_translate("Form", "Save Picture", None))
        self.checkBox_Grid.setText(_translate("Form", "Grid", None))
        self.groupBox_3.setTitle(_translate("Form", "FBG Output ", None))
        self.textEdit_FBGoutput.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.actionSavePicture.setText(_translate("Form", "SavePicture", None))

